language: c++
compiler: gcc
sudo: required
before_install:
- sudo apt-get update
install:
- sudo apt-get install python3
script:
  - python3 --version
  - export WORKSPACE=$PWD/huningxin/ostro-os-xt
  - mkdir -p $WORKSPACE
  - cd $WORKSPACE
  - git clone --recursive https://github.com/ostroproject/ostro-os-xt .
  - source ostro-init-build-env
  - bitbake ostro-xt-image-noswupd