language: python
sudo: required
script:
  - python --version
  - python3 --version
  - export WORKSPACE=$PWD/huningxin/ostro-os-xt
  - mkdir -p $WORKSPACE
  - cd $WORKSPACE
  - git clone --recursive https://github.com/ostroproject/ostro-os-xt .
  - source ostro-init-build-env
  - bitbake ostro-xt-image-noswupd